reddit_clone/config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:create, :show]
  resources :posts do
    resources :comments, only: :new
  end
  resources :subs 
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resource :session, only: [:new, :create, :destroy]
end

reddit_clone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  url        :string           not null
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Post < ApplicationRecord

  validates :title, :url, presence: true

  has_many :post_subs, dependent: :destroy, inverse_of: :post
  has_many :subs, through: :post_subs
  belongs_to :author,
    foreign_key: :user_id,
    class_name: :User
  has_many :comments
end

reddit_clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :validate_login

  def show
    @post = Post.includes(comments: [:user]).find_by(id: params[:id])
  end
  
  def new
    @post = Post.new
  end
  
  def edit
    @post = Post.find_by(id: params[:id])
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to post_url(@post)      
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def update
    @post = current_user.posts.find_by(id: params[:id])

    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :url, :content, sub_ids: [])
    end
end

reddit_clone/app/helpers/posts_helper.rb
module PostsHelper
end

reddit_clone/app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

reddit_clone/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

reddit_clone/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @posts %>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.title %></td>
          <td><%= link_to 'Show', post %></td>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

reddit_clone/app/views/posts/new.html.erb
<%= flash.now[:errors] if flash.now[:errors] %>
<h1>Create New Post</h1>

<form action="<%= posts_url %>" method="POST">
  <%= render "shared/auth" %>
  <label>Title:  
    <input type="string" name="post[title]" value="<%= @post.title %>">
  </label>
  <label>URL: 
    <input type="string" name="post[url]" value="<%= @post.url %>">
  </label>
  <label>Content: 
    <input type="text" name="post[content]" value="<%= @post.content %>">
  </label>

  <input type="hidden" name="post[sub_ids][]" value="">
  <% Sub.all.each do |sub| %>
    <label><%= sub.title %>
      <input
        type="checkbox"
        value="<%= sub.id %>"
        name="post[sub_ids][]"
        <%= "checked" if @post.sub_ids.include?(sub.id) %>
      />
    </label>
  <% end %>

  <input type="submit" value="Create New Post">

</form>


<%= link_to 'Back', posts_path %>

reddit_clone/app/views/posts/show.html.erb
<h1><a href="<%= post_url(@post) %>"><%= @post.title %></a> 
    by <%= @post.author.username %></h1>

<p>Content:
  <%= @post.content %>
</p>

Subs
<ul>
  <% @post.subs.each do |sub| %>
    <li><a href="<%= sub_url(sub) %>"><%= sub.title %></a></li>
  <% end %>
</ul>

<h2>Comments</h2>
<a href="<%= new_post_comment_url(@post) %>">Add a Comment!</a>

<ul>
<% if @post.comments %>
  <% @post.comments.where(parent_comment_id: nil).each do |comment| %>
    <li>
      <a href="<%= comment_url(comment) %>"><%= comment.content %></a>
      <!--Recursively iterate through children-->
      <%= render 'shared/comment', comment: comment %>
    </li>
  <% end %>
<% end %>
</ul>



<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>