reddit_clone/config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:create, :show]
  resources :posts do
    resources :comments, only: :new
  end
  resources :subs 
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resource :session, only: [:new, :create, :destroy]
end

reddit_clone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :bigint(8)        not null, primary key
#  title       :string           not null
#  description :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

class Sub < ApplicationRecord

  validates :title, :description, presence: true

  belongs_to :moderator,
    foreign_key: :user_id,
    class_name: :User

  has_many :post_subs, dependent: :destroy, inverse_of: :sub
  has_many :posts, through: :post_subs, source: :post

end

reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :validate_login

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find_by(id: params[:id])
  end

  def new
    @sub = Sub.new
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id

    if @sub.save
      redirect_to subs_url
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def update
    @sub = current_user.subs.find_by(id: params[:id])


    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
      
  end

  private
    def sub_params
      params.require(:sub).permit(:title, :description)
    end
end

reddit_clone/app/helpers/subs_helper.rb
module SubsHelper
end

reddit_clone/app/views/subs/_form.html.erb
<%= form_with(model: sub, local: true) do |form| %>
  <% if sub.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sub.errors.count, "error") %> prohibited this sub from being saved:</h2>

      <ul>
      <% sub.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

reddit_clone/app/views/subs/edit.html.erb
<%= flash.now[:errors] if flash.now[:errors] %>
<h1>Edit Sub</h1>

<form action="<%= sub_url(@sub) %>" method="POST">
  <input type="hidden" name="_method" value="patch">
  <%= render "shared/auth" %>
  <label>Title:  
    <input type="string" name="sub[title]" value="<%= @sub.title %>">
  </label>
  <label>Description: 
    <input type="text" name="sub[description]" value="<%= @sub.description %>">
  </label>
  <input type="submit" value="Edit Sub">

</form>

<%= link_to 'Back', subs_path %>

reddit_clone/app/views/subs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subs.each do |sub| %>
      <tr>
        <td><a href="<%= sub_url(sub) %>"><%= sub.title %></a></td>
        <td><%= link_to 'Show', sub %></td>
        <td><%= link_to 'Edit', edit_sub_path(sub) %></td>
        <td><%= link_to 'Destroy', sub, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sub', new_sub_path %>

reddit_clone/app/views/subs/new.html.erb
<%= flash.now[:errors] if flash.now[:errors] %>
<h1>Create New Sub</h1>

<form action="<%= subs_url %>" method="POST">
  <%= render "shared/auth" %>
  <label>Title:  
    <input type="string" name="sub[title]" value="<%= @sub.title %>">
  </label>
  <label>Description: 
    <input type="text" name="sub[description]" value="<%= @sub.description %>">
  </label>
  <input type="submit" value="Submit">

</form>


<%= link_to 'Back', subs_path %>

reddit_clone/app/views/subs/show.html.erb
<p id="notice"><%= notice %></p>

<%= @sub.title %>

<label>Description<br>
  <%= @sub.description %>
</label>

<a href="<%= new_post_url %>">Make New Post!</a>

<% if @sub.posts %>
  <ul>
    <% @sub.posts.each do |post| %>
      <li><a href="<%= post_url(post) %>"><%= post.title %></a>
      </li>
    <% end %>
  </ul>
<% end %>

<%= link_to 'Edit', edit_sub_path(@sub) %> |
<%= link_to 'Back', subs_path %>