reddit_clone/config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:create, :show]
  resources :posts do
    resources :comments, only: :new
  end
  resources :subs 
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resource :session, only: [:new, :create, :destroy]
end

reddit_clone/app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id                :bigint(8)        not null, primary key
#  content           :text             not null
#  user_id           :integer          not null
#  post_id           :integer          not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  parent_comment_id :integer
#

class Comment < ApplicationRecord

  validates :content, presence: true

  belongs_to :user
  belongs_to :post
  belongs_to :parent_comment,
    optional: true,
    foreign_key: :parent_comment_id,
    class_name: :Comment

  has_many :child_comments,
    foreign_key: :parent_comment_id,
    class_name: :Comment
end

reddit_clone/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :validate_login

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id 
    @comment.parent_comment_id = params[:comment][:parent_comment_id]
    @comment.post_id = params[:comment][:post_id] || @comment.parent_comment.post_id

    
    if @comment.save
      redirect_to post_url(@comment.post)
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  def show
    @comment = Comment.find_by(id: params[:id])
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :post_id, :parent_comment_id)
    end
end

reddit_clone/app/helpers/comments_helper.rb
module CommentsHelper
end

reddit_clone/app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

reddit_clone/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

reddit_clone/app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

reddit_clone/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= flash.now[:errors] if flash.now[:errors] %>

<form action="<%= comments_url %>" method="POST">
  <input type="hidden" name="post_id" value="<%= params[:post_id] %>">
  <input type="hidden" name="comment_id" value="<%= params[:id] %>">
  <%= render "shared/auth" %>
  <label>Body:  
    <input type="text" name="comment[content]" value="<%= @comment.content %>">
  </label>
  <input type="submit" value="Submit">

</form>


<%= link_to 'Back', comments_path %>

reddit_clone/app/views/comments/show.html.erb
<%= @comment.content %>

<h3>Reply to this comment</h3>

<form action="<%= comments_url %>" method="POST">
  <input type="hidden" name="comment[post_id]" value="<%= @comment.post_id %>">
  <input type="hidden" name="comment[parent_comment_id]" value="<%= params[:id] %>">
  <%= render "shared/auth" %>
  <label>Body:
    <input type="text" name="comment[content]">
  </label>
  <input type="submit" value="submit">
</form>

<%= link_to 'Back', comments_path %>